### ISSUE TITLE
Api calls for context creation

### ISSUE THREAD

**Issue by anban4u** [anban4u/dashboard#2]
Need apis for 
1. AllSellingAccounts (partner specific)
2. Get distinct contexts 
3. Get paginated context list (filtered by platform, country)
4. Save propertycontext

Assigning to @abhinav-sati

**Comment by k-abhinav** [comment]
Apis created successfully.

**Comment by anban4u** [comment]
In getsellingaccounts call use partner prefix in header.

**Comment by anban4u** [comment]
Also, the platform is enum. Please provide its string

**Comment by anban4u** [comment]
We need to return enum strings for all calls

**Comment by k-abhinav** [comment]
GetAllSellingAccounts() call update successfully with header of
PartnerPrefix.


Thanks & Regards

* Kumar Abhinav*

**Comment by k-abhinav** [comment]
Set Enum formatter at api global config, So all calls return enum as
strings.


Thanks & Regards

* Kumar Abhinav*

**Comment by k-abhinav** [comment]
done


Thanks & Regards

* Kumar Abhinav*
